import type { Product } from "../demo-types";
export const products: Product[] = [
  ...(["imperium", "arcodia"] as const).map((id) => ({
    id,
    name: { key: "retractable" } as const,
    category: "retractable" as const,
    model: id.charAt(0).toUpperCase() + id.slice(1),
    description: { key: "specifications" } as const,
    options: "",
    active: true,
  })),
  ...(["eira", "liniar"] as const).map((id) => ({
    id,
    name: { key: "bioclimatic" } as const,
    category: "bioclimatic" as const,
    model: id.charAt(0).toUpperCase() + id.slice(1),
    description: { key: "specifications" } as const,
    options: "",
    active: true,
  })),
  {
    id: "wintergarden",
    name: "Wintergarden",
    category: "other",
    model: "Wintergarden",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
  {
    id: "majestic",
    name: { key: "retractable" },
    category: "retractable",
    model: "Majestic",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
  {
    id: "bioclimatic",
    name: { key: "bioclimatic" },
    category: "bioclimatic",
    model: "Aeris",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
  {
    id: "runglass",
    name: "Runglass",
    category: "slidingGlass",
    model: "Run",
    description: { key: "slidingGlass" },
    options: "",
    active: true,
  },
  {
    id: "thermoglass",
    name: "Thermoglass",
    category: "slidingGlass",
    model: "Thermo",
    description: { key: "slidingGlass" },
    options: "",
    active: true,
  },
  {
    id: "tripleglass",
    name: "Tripleglass",
    category: "tripleglass",
    model: "Triple",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
  {
    id: "screenzip",
    name: "Screen Zip",
    category: "screenZip",
    model: "Zip",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
  {
    id: "skyzip",
    name: "Sky Zip",
    category: "other",
    model: "Sky",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
  {
    id: "other",
    name: { key: "other" },
    category: "other",
    model: "",
    description: { key: "specifications" },
    options: "",
    active: true,
  },
];
